application: astromonitorapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: astromonitorapp.application
- url: /transients
  script: astromonitorapp.application

libraries:
- name: webapp2
  version: latest